#!/usr/bin/env bash
set -euo pipefail

# This is a preview generated by V24. The Python executor requires explicit --approve.

# prepare_reference_manifest: 把 split 转成 train/test/reference manifest。
/data1/huangyuling/bin/python iad_mvp/scripts/prepare_iad_reference_manifest.py --split iad_mvp/data/mvtec_split.json --output iad_mvp/data/iad_reference_manifest.jsonl

# build_reference_bank: 构建 normal reference feature bank。
/data1/huangyuling/bin/python iad_mvp/scripts/build_reference_bank.py --manifest iad_mvp/data/iad_reference_manifest.jsonl --output_dir iad_mvp/data

# reproduce_lightweight_baseline: 复现 lightweight nearest-reference baseline。
/data1/huangyuling/bin/python iad_mvp/scripts/run_iad_baselines.py --manifest iad_mvp/data/iad_reference_manifest.jsonl --reference_bank iad_mvp/data/iad_reference_bank.npz --output_dir iad_mvp/outputs/patchcore_baseline

# run_reference_consistency_agent: 运行 reference-consistency scoring / agent decision。
/data1/huangyuling/bin/python iad_mvp/scripts/score_reference_consistency.py --manifest iad_mvp/data/iad_reference_manifest.jsonl --baseline iad_mvp/outputs/patchcore_baseline/iad_baseline_scores.csv --reference_bank iad_mvp/data/iad_reference_bank.npz --reference_index iad_mvp/data/iad_reference_index.jsonl --output iad_mvp/outputs/reference_consistency/iad_reference_consistency_scores.csv --anomaly_threshold 0.5 --consistency_threshold 0.55

# evaluate_execution_metrics: 汇总 IAD execution metrics。
/data1/huangyuling/bin/python iad_mvp/scripts/evaluate_iad_agent.py --baseline iad_mvp/outputs/patchcore_baseline/iad_baseline_scores.csv --scores iad_mvp/outputs/reference_consistency/iad_reference_consistency_scores.csv --output_dir iad_mvp/outputs/tables --threshold 0.5
