#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

from common_iad import read_csv, simple_auc, write_csv


def main() -> None:
    parser = argparse.ArgumentParser(description="Evaluate lightweight IAD agent scaffold outputs.")
    parser.add_argument("--baseline", type=Path, default=Path("iad_mvp/outputs/patchcore_baseline/iad_baseline_scores.csv"))
    parser.add_argument("--scores", type=Path, default=Path("iad_mvp/outputs/reference_consistency/iad_reference_consistency_scores.csv"))
    parser.add_argument("--output_dir", type=Path, default=Path("iad_mvp/outputs/tables"))
    parser.add_argument("--threshold", type=float, default=0.5)
    args = parser.parse_args()

    if not args.baseline.exists():
        raise SystemExit(f"Missing baseline score file: {args.baseline}")
    if not args.scores.exists():
        raise SystemExit(f"Missing reference consistency score file: {args.scores}")

    baseline_rows = read_csv(args.baseline)
    score_rows = read_csv(args.scores)
    labels = [int(row["label"]) for row in baseline_rows]
    baseline_scores = [float(row["baseline_score"]) for row in baseline_rows]
    auc = simple_auc(labels, baseline_scores)

    normal_rows = [row for row in score_rows if int(row["label"]) == 0]
    baseline_false_alarms = sum(1 for row in normal_rows if float(row["baseline_score"]) >= args.threshold)
    agent_false_alarms = sum(1 for row in normal_rows if row["decision"] == "accept_anomaly")
    if baseline_false_alarms:
        false_alarm_reduction = (baseline_false_alarms - agent_false_alarms) / baseline_false_alarms
    else:
        false_alarm_reduction = 0.0

    evidence_grounding = sum(1 for row in score_rows if row.get("nearest_reference_image_path")) / len(score_rows)
    tool_success_rate = sum(1 for row in score_rows if row.get("decision")) / len(score_rows)
    summary_rows = [{
        "image_level_auc_lightweight": "" if auc is None else f"{auc:.6f}",
        "baseline_false_alarms_at_threshold": baseline_false_alarms,
        "agent_false_alarms_at_threshold": agent_false_alarms,
        "false_alarm_reduction_proxy": f"{false_alarm_reduction:.6f}",
        "evidence_grounding_score_proxy": f"{evidence_grounding:.6f}",
        "tool_success_rate": f"{tool_success_rate:.6f}",
        "note": "scaffold metrics; not final benchmark results",
    }]

    args.output_dir.mkdir(parents=True, exist_ok=True)
    csv_path = args.output_dir / "iad_agent_execution_metrics.csv"
    md_path = args.output_dir / "iad_agent_execution_summary.md"
    write_csv(csv_path, summary_rows)
    md_path.write_text(
        "# IAD Agent Execution Summary (Scaffold)\n\n"
        "This file is generated by the v1.2 scaffold. It is not a final benchmark report.\n\n"
        + "\n".join(f"- {key}: {value}" for key, value in summary_rows[0].items())
        + "\n",
        encoding="utf-8",
    )
    print(f"Saved: {csv_path}")
    print(f"Saved: {md_path}")


if __name__ == "__main__":
    main()
